Repository Reainheart/OmniNode, pull requests merged in 2024-03, with the labels that each got.

#29 Instruct-Page buttons
  client/src/Pages/Instruct-Page/Instruct-Page.css
  client/src/Pages/Instruct-Page/Instruct-Page.jsx
Labels: enhancement

#31 28 clicking on the canvas creates a completely white page that cant be escaped
  api/SB/GetNodeLearnPage.js
  api/SB/GetSampleCodeNode.js
  api/index.js
  api/package-lock.json
  api/package.json
  client/src/Global/header/Header.jsx
Labels: bug, documentation, enhancement

#30 Learning-Tool-Menu
  client/src/Pages/home/Components/Learning-Tool-Menu/Code-View/Code-View.jsx
  client/src/Pages/home/Components/Learning-Tool-Menu/Learning-Tool-Menu-View/Learning-Tool-Menu/Learning-Tool-Menu.css
  client/src/Pages/home/Components/Learning-Tool-Menu/Learning-Tool-Menu-View/Learning-Tool-Menu/Learning-Tool-Menu.jsx
  client/src/Pages/home/Components/Learning-Tool-Menu/Learning-Tool-Menu-View/Learning-Tool-View-Window/Learning-Tool-View-Window.css
  client/src/Pages/home/Components/Learning-Tool-Menu/Learning-Tool-Menu-View/Learning-Tool-View-Window/Learning-Tool-View-Window.jsx
  client/src/Pages/home/Components/Learning-Tool-Menu/Learning-Tool-Menu-View/View-Selection-Menu/View-Selection-Menu.css
  client/src/Pages/home/Components/Learning-Tool-Menu/Learning-Tool-Menu-View/View-Selection-Menu/View-Selection-Menu.jsx
  client/src/Pages/home/Home.jsx
  client/src/Pages/home/home.css
Labels: bug, enhancement, help wanted

#45 Can now pull API and display API data in the code-view
  api/index.js
  api/package-lock.json
  api/package.json
  client/src/Pages/home/Components/Learning-Tool-Menu/Code-View/Code-View.jsx
Labels: enhancement

#49 Node now displays on the canvas
  client/src/Pages/home/Components/Canvas/CanvasComponent.jsx
  client/src/Pages/home/Components/Canvas/Node/Node.css
  client/src/Pages/home/Components/Canvas/Node/Node.jsx
Labels: enhancement

#51 About page now has content
  client/src/App.jsx
  client/src/Pages/Instruct-Page/Instruct-Page.css
  client/src/Pages/header/about/About.jsx
  client/src/Pages/header/about/about.css
  client/src/Pages/home/Components/Canvas/CanvasComponent.jsx
  client/src/Pages/home/Components/Canvas/Node/Node.css
  client/src/Pages/home/Components/Learning-Tool-Menu/Learning-Tool-View-Window/Learning-Tool-View-Window.jsx
Labels: documentation, enhancement
